# Generated by Django 3.1.7 on 2021-03-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210324_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
